### ISSUE TITLE
Share Pre-trained weight with Google Drive

### ISSUE THREAD

**Issue by developer0hye** [yjh0410/pytorch-yolo-v2#2]
Thanks for sharing your great works.

I tried to download your ImageNet pretrained weight file with baidu. But I failed to it.

Could you share pre-trained weight with Google drive?

**Comment by developer0hye** [comment]
@yjh0410 
Finally, I downloaded the pretrained weight file with Baidu. If you are okay, I can upload this to my Google Drive and  share the link on this repository.

**Comment by yjh0410** [comment]
Oh, thanks a lot!&nbsp;
If you don't mind to upload it to your Googld Drive, just do it. I'll appreciate it！
I tried the whole day but failed to upload ...&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月13日(星期五) 下午3:51
收件人:&nbsp;"yjh0410/pytorch-yolo-v2"<pytorch-yolo-v2@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/pytorch-yolo-v2] Share Pre-trained weight with Google Drive (#2)





 
@yjh0410
 Finally, I downloaded the pretrained weight file with Baidu. If you are okay, I can upload this to my Google Drive and  share the link on this repository.
